import type { Metadata } from "next";

import { IcecastPlayerComponent } from "@/components/icecast-player/dynamic.component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function (): PageProps<"/"> {
  return (
    <div>
      <IcecastPlayerComponent
        streamUrl={
          process.env.NEXT_PUBLIC_STREAM_URL ||
          "http://localhost:8000/radio.mp3"
        }
      />
    </div>
  );
}
